### ISSUE TITLE
k-columns "type" ignored: All columns treated as strings in grid when filtering

### ISSUE THREAD

**Issue by mschwaibold** [kendo-labs/angular-kendo#104]
I tried to convert a demo from KendoUI to a directives version  as seen in this plunk

http://plnkr.co/edit/pWt3HDonbCTTkBYn1UP6?p=preview

Compared to the version without directives I noticed, that the filter menu in the column header does not reflect the datatype, Instead a filter for string values is shown for every column. I can select "Starts with" on date and number columns now!?

Is there a way to show the proper filters using directives?

What I expected to see was http://plnkr.co/edit/QqBi9UckaEbT1pkisb5h?p=preview, see "Age" and "Bitrth Date" columns.

**Comment by hidegh** [comment]
Still buggy in 2015.2.805
If you configure the grid via a DataSource object (grid settings -- dataSource: dataSrc), the grid filters will be all for strings, even if column types are defined. If you get the object and configure grid with it inline dataSource: { ... } then everything is ok.
