### ISSUE TITLE
k-on-data-bound does not work on kendo-grid

### ISSUE THREAD

**Issue by mschwaibold** [kendo-labs/angular-kendo#126]
I want to add a special style to some rows, depending on the data. That works only on paging to the next grid page, never on the initial loading of the data.

Plunk: http://plnkr.co/edit/javnR6otNwFRG6lhMq5T?p=preview

By the way: In issue 27 is a plunk with an older angular-kendo.js where that event handler actually executed on initialization, not only on paging.

**Comment by saber13812002** [comment]
i'm also solve this issue in angular with dataBound :

my issue about kendo auto fit columns in databound

                <kendo-grid id="grid" options="mainGridOptions">
                </kendo-grid>



                dataBound: function(){
                    var grid = $("#grid").data("kendoGrid");
                    for (var i = 0; i < grid.columns.length; i++) {
                        grid.autoFitColumn(i);
                    }
                },
                dataSource: $scope.data,
