### ISSUE TITLE
Scheduler k-on-change binding not working

### ISSUE THREAD

**Issue by kattax** [kendo-labs/angular-kendo#163]
I am using the scheduler widget, and I need to capture the event where the user clicks on an event in the scheduler. 

From the Scheduler documentation, I believe this is the "change" event. I have tried both inserting the "k-on-change=selectEvent(kendoEvent)" attribute into the html:

<div kendo-scheduler k-options="calendarOptions" k-data-source="schedule" k-on-navigate="navigateCalendar(kendoEvent)" k-on-save="saveCalendarEvent(kendoEvent)" k-on-change="selectEvent(kendoEvent)"></div>

 as well as inserting the "change" parameter into the calendar options:

$scope.calendarOptions={
        views: [
            "day",
            { type: "week", selected: true },
            "workWeek",
            "month"
        ],
        showWorkHours:true,
        change:function(e){
            var x = dosomethingawesome();
        }

Neither are firing when the user clicks an event in the scheduler. I would love to get some help with this! Thanks!

**Comment by TheRealYeronimo** [comment]
This is still not reflected in documentation or demo's. This solved my problem, but is nowhere to be found as required for the change even to be fired

**Comment by scottfwalter** [comment]
OMG thank you for posting about this.   I have been working on this for over an hour.  I don't understand why its not documented.
