### ISSUE TITLE
k-position isn't working in tooltip

### ISSUE THREAD

**Issue by YonatanKra** [kendo-labs/angular-kendo#199]
Hi,
I'm trying to implement the tooltip with the plugin.
The positioning works if I add it to the opts variable, but I can't set the tooltip position from the view.
Here's my plunk:
http://plnkr.co/edit/5Xe7w3uFbbgwT3HaW9YE?p=preview

**Comment by johnsathe** [comment]
k-tooltip="'top'" doesnt work...

**Comment by yccteam** [comment]
It's ```k-position: "top" ```.
Try to change it here: http://plnkr.co/edit/XF3PFsQ8MmzXHX93OhUi?p=preview
