### ISSUE TITLE
Kendo grid with remote data and DataSourceResult

### ISSUE THREAD

**Issue by jkbrito** [kendo-labs/angular-kendo#213]
I'm having trouble with remote data kendo grid .

I'm trying to use a WebAPI that returns the object DataSourceResult

[Route("banco/grid")]
        public DataSourceResult GetFiltered([FromUri] DataSourceRequest request)
        {
            var x = new List<BancoDTO>()
                    {
                        new BancoDTO()
                        {
                            Id = Guid.NewGuid(),
                            Codigo = "001",
                            Nome = "Teste"
                        },
                         new BancoDTO()
                        {
                            Id = Guid.NewGuid(),
                            Codigo = "001",
                            Nome = "Teste"
                        },  
                    };
            return x.AsQueryable().ToDataSourceResult(request);
        }
    }

The grid in my template..

<div kendo-grid k-data-source="Grid" k-selectable="'row'"
     k-pageable='{ "refresh": true, "pageSizes": true }'
     k-columns='[ "Id", "Codigo", "Nome" ]'     
     k-sortable="true" k-filterable="true">
</div>

And angular controller ...

     $scope.Grid = new kendo.data.DataSource({
        type: "odata",
        transport: {
            read: "Api/banco/grid"
        },
        schema: {
            model: {  
                fields: {
                    Id: { type: "string" },
                    Codigo: { type: "string" },
                    Nome: { type: "string" },
                }
            }
        },
    });

The grid does not display the same results running the API call. 

The json that is returned from call ... 

{"Data":[{"Codigo":"001","Nome":"Teste","Id":"84e09cf8-66e1-4a94-bb5b-9de285e9cc82"},{"Codigo":"001","Nome":"Teste","Id":"fcc9b134-ec96-43cf-8b82-412ab567cb99"}],"Total":6,"AggregateResults":null,"Errors":null}

Can anyone help me?

**Comment by aaroncalderon** [comment]
@mishoo I am curios, how would you implement the links into the table. Possibly how would you edit it too... I was able to get the [links info to display](http://plnkr.co/edit/BNSDKeFjazcHgxyfVKyo?p=preview) on the table by adding `{'field': 'links[0].rel', 'title': 'Link'}]` in the index.html file. But, I got lost after that. My changes pretty much broke the `add new record` button.

Thanks.
