### ISSUE TITLE
kendo-grid datasource doesn't refresh / bind

### ISSUE THREAD

**Issue by dsoltesz** [kendo-labs/angular-kendo#33]
when using kendo-grid if you define data up front grid will display data.  If you want to delay loading the data (ie fetch from file, server etc) the grid doesn't render/re-bind.  I created a plunker to demonstrate, hopefully I'm just doing something wrong.

http://plnkr.co/edit/MUbU7oq8lmvmcDNviGGp?p=preview

**Comment by kamilwasyl** [comment]
but the problem is when you use k-rebind attribute then if you had <div k-detail-template> there for expanding then after rebind/refresh this column with expander disapears... any thoughts how to solve it ?
