### ISSUE TITLE
Template support

### ISSUE THREAD

**Issue by marklagendijk** [kendo-labs/angular-kendo#34]
A very powerful feature of Kendo UI is its customizability. An important part of this are the templates: the default HTML of certain (parts of) controls can be replaced by specifying your own custom template.

A good example of this is the Grid control. The [Grid](http://docs.kendoui.com/api/web/grid) has the following templates:
- altRowTemplate
- columns.footerTemplate
- columns.groupHeaderTemplate
- columns.groupFooterTemplate
- columns.headerTemplate
- columns.template
- detailTemplate
- editable.template
- rowTemplate
- toolbar.template

Can these options already be used, in a way which makes sense, when you are using Angular-Kendo? 
I suppose that setting them using templates as string would work, but you don't want to specify templates inline in the HTML attribute, or in your controller.

Would it be possible to support using Angular templates in these cases, so you could use `ng-click` etc? This would be a very nice feature.
I think, however, that the code for this would have to be in Kendo UI itself. This is because the templates would have to be [$compiled](http://docs.angularjs.org/api/ng.$compile) with the right `$scope`. I doubt whether it would be possible to add this feature from 'outside' of Kendo UI (via Angular-Kendo).

Let me know what your thoughts are about this :).

**Comment by UsmanHaideer** [comment]
when i use template function in kendo like template:function (dataitem){return "<span pass-object="+dataitem.CompnayID+"></span>"} pass-object is angular directive which is not working in template how it can be solved ??
