### ISSUE TITLE
kendo-tab-strip-if  possible  implementations

### ISSUE THREAD

**Issue by leblancmeneses** [kendo-labs/angular-kendo#390]
I have a lot of controls on these tabs and it's causing a performance problem.

One possible fix is to use ng-if/ng-swith based on the selected tab  to destroy $scopes/dom controls not in use.

Two implementations exist each with their own set of problems to deal with:
1) Use a $scope property around to track the name of the tab

1.1 

```
  <div kendo-tab-strip ext-tab-strip-if='["TabNotes","tabName2"]'>
```

1.2

```
    <div ng-switch="TabStripMetadata.TabSelectedByName">
        <div ng-switch-when="TabNotes">
            @Html.Partial("TabNotes")
        </div>
        <div ng-switch-default>
            {{TabStripMetadata.TabSelectedByName}}
        </div>
    </div>
```
#### _IT WOULD REALLY HELP TO GIVE A VISUAL STRUCTURE OF SCOPES/ISOLATED SCOPES CREATED BY THE CONTROLS_

with the prototypical inheritance I haven't found a <strong>reliable</strong> way to do this.  Without docs of scopes (batarang, ng-inspector - are not reliable and shouldn't be required on commercial controls that should be documented) it will take a ramp of time that shouldn't be necessary.

Example: http://www.telerik.com/help/silverlight/gridview-visual-structure.html
![radgridview_visualstructure_1 1](https://cloud.githubusercontent.com/assets/730804/4428517/7960477c-45cd-11e4-89d0-77ecef3d442f.png)

2) Another approach is to use a directive that mimics ng-if based required kendoTabStrip/kendoTabstrip - both are registered in the angular.module....

I think this is the cleanest approach since I'm not dealing with prototypical inheritance problems.  However, require isn't working for kendo controls probably because the directive controller is defined but empty.  That means I have to do hacky stuff to get back to the tabstrip instance when it should have been as easy as requiring ^kendoTabStrip  and kendoTabStrip.get()

see for yourself:  http://dojo.telerik.com/IruwI

```
<div ng-controller="MyCtrl">
    <div kendo-tab-strip k-content-urls="[ null, null]">
      <!-- tab list -->
      <ul>
        <li class="k-state-active">First tab</li>
        <li>Second tab</li>
      </ul>

      <div style="padding: 1em">
        <kendo-tab-strip-if>
          I am removed from dom + scope destroyed
        </kendo-tab-strip-if>
      </div>

      <div style="padding: 1em">
        This is the second tab
      </div>
    </div>
</div>
```

I am just a little frustrated for the hoops I have to jump and airing out a few of the problems I am seeing when building a simple directive extension.

**Comment by kathannshea** [comment]
@leblancmeneses 

Can you help me understand your full implemented solution.  I have the same problem with too many items on the tabs.
