### ISSUE TITLE
Is "angular-kendo.js" free to use?

### ISSUE THREAD

**Issue by amardhere** [kendo-labs/angular-kendo#408]
Can you give answers of followings -
Is "angular-kendo.js" free to use in the application? 
Is it required any license cost ? 
Is "angular-kendo.js" part of Kendo or separately developed ?

**Comment by RobHarrisAZ** [comment]
I think this separate repo of Angular-Kendo is now depricated and is included in the main KendoUI repo now..

**Comment by tsvetomir** [comment]
As @RobHarrisAZ confirmed, AngularJS integration is now [built-in](http://docs.telerik.com/kendo-ui/AngularJS/introduction) in Kendo UI for jQuery.

Please note that this is the issue tracker of the [Kendo UI for Angular](http://www.telerik.com/kendo-angular-ui/) suite. Please submit your questions through the [Kendo UI Core issue tracker](https://github.com/telerik/kendo-ui-core/issues) or the  [ticketing system](http://www.telerik.com/account/support-tickets/available-support-list) to get assistance.
