### ISSUE TITLE
k-rebind listview

### ISSUE THREAD

**Issue by stella-di** [kendo-labs/angular-kendo#409]
Hi!
How I can use k-rebind in kendo-listview?

**Comment by tsvetomir** [comment]
This is the issue tracker of the [Kendo UI for Angular](http://www.telerik.com/kendo-angular-ui/) suite. 

The question appears to be for Kendo UI for jQuery. Please submit a [support ticket]
(http://www.telerik.com/account/support-tickets/available-support-list) to get assistance.
