### ISSUE TITLE
Grid with groupable property causes error message when navigating to another page

### ISSUE THREAD

**Issue by fongcn** [kendo-labs/angular-kendo#66]
I have a Grid that has the groupable property set to true.  When I navigate to another page in my app, I get the following error in my console:

Error: Cannot call method 'destroy' of kendoDropTarget before it is initialized

I see a similar error message when I have the reordable property set as well.

Here's a plunker that demonstrates the problem. 
http://plnkr.co/edit/2tVXsHBw5zWZbwqPuk6D

It doesn't seem to affect my app behavior, but it would be nice to know why this is happening.

**Comment by Siafu** [comment]
I'm having this issue with the latest build of Kendo UI 2016.1.226 and Angular 1.5. I have included the kendo.all.min.js and kendo.angular.min.js scripts.

**Comment by MLefebvreICO** [comment]
Having the same issue with Kendo UI 2016.1.226 and Angular 1.5. Only `kendo.all.js` is loaded on top on Angular

**Comment by MartijnKuipers** [comment]
I'm using 2016.3.118 and angular 1.5.11. If I build a grid with { groupable : true } and then move away from the page by changing its $state, I also receive the error. 

However, if I do not make the grid groupable, there is no such error. 

Also, if I make the grid groupable, create a group, then it will destroy the grid just fine.

My workaround is to set a group before leaving the page. The group does not have to exist, so in my case I do:
	$scope.measurementDS.group({ field: "none" });
`

(There is no "none" field, but now it closes just fine.

Note: I am not using serverGrouping. Using this workaround with serverGrouping will probably entail a call to the server.
